/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminEventAdd: typeof import('./src/components/AdminEventAdd.vue')['default']
    AdminEventEdit: typeof import('./src/components/AdminEventEdit.vue')['default']
    AdminNavbar: typeof import('./src/components/AdminNavbar.vue')['default']
    ButtonCustom: typeof import('./src/components/atomics/ButtonCustom.vue')['default']
    CardHomeBlog: typeof import('./src/components/atomics/CardHomeBlog.vue')['default']
    CardHomeVideo: typeof import('./src/components/atomics/CardHomeVideo.vue')['default']
    CardKamus: typeof import('./src/components/atomics/CardKamus.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HeroBanner: typeof import('./src/components/HeroBanner.vue')['default']
    HomeBlog: typeof import('./src/components/HomeBlog.vue')['default']
    HomeHero: typeof import('./src/components/HomeHero.vue')['default']
    HomeJobSeeking: typeof import('./src/components/HomeJobSeeking.vue')['default']
    HomeShop: typeof import('./src/components/HomeShop.vue')['default']
    HomeVideo: typeof import('./src/components/HomeVideo.vue')['default']
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    IconBack: typeof import('./src/components/icons/IconBack.vue')['default']
    IconCalendar: typeof import('./src/components/icons/IconCalendar.vue')['default']
    IconDown: typeof import('./src/components/icons/IconDown.vue')['default']
    IconHamburger: typeof import('./src/components/icons/IconHamburger.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconInvisible: typeof import('./src/components/icons/IconInvisible.vue')['default']
    IconProfile: typeof import('./src/components/icons/IconProfile.vue')['default']
    IconScreen: typeof import('./src/components/icons/IconScreen.vue')['default']
    IconVisible: typeof import('./src/components/icons/IconVisible.vue')['default']
    LayoutNavbar: typeof import('./src/components/LayoutNavbar.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    LogoutModal: typeof import('./src/components/LogoutModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarAdmin: typeof import('./src/components/SidebarAdmin.vue')['default']
    UnauthorizedModal: typeof import('./src/components/UnauthorizedModal.vue')['default']
  }
}
