/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AtendeeDetails: typeof import('./src/components/AtendeeDetails.vue')['default']
    ContactDetails: typeof import('./src/components/ContactDetails.vue')['default']
    Details: typeof import('./src/components/Details.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    ListEvent: typeof import('./src/components/atomics/ListEvent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
  }
}
